### ISSUE TITLE
Package is not on pip, but the README says so

### ISSUE THREAD

**Issue by cmarqu** [wallento/cocomod-wishbone#16]
This package is not on pip, but the README says so - just upload it? :)

**Comment by wallento** [comment]
Ah, right, I think that's where I stopped when we started the discussion about the naming. I need to refresh my mind, what was the name we decided to go with? :)

**Comment by cmarqu** [comment]
``cocotbext`` is good, see https://docs.cocotb.org/en/latest/extensions.html#naming-conventions

**Comment by wallento** [comment]
Ah, very good. Sorry, I lost a bit of traction during the discussion we had on the issue. I will add a GH action to do it now.

**Comment by Martoni** [comment]
Seems to be solved :

```shell
$ python -m pip install cocotbext-wishbone --no-cache-dir
Collecting cocotbext-wishbone
  Downloading cocotbext_wishbone-0.2-py3-none-any.whl (7.8 kB)
Requirement already satisfied: cocotb in /home/user/.local/lib/python3.8/site-packages (from cocotbext-wishbone) (1.4.0)
Installing collected packages: cocotbext-wishbone
Successfully installed cocotbext-wishbone-0.2
```
