### ISSUE TITLE
The 'cocotb.drivers' package has been moved to 'cocotb_bus.drivers'.

### ISSUE THREAD

**Issue by thejpster** [wallento/cocomod-wishbone#18]
There is a deprecation warning using cocotb 1.5.2.

If you use cocotb 1.6.0-rc1, this crate no longer works, complaining it can't find `cocotb.drivers.BusDriver`.

**Comment by Roenski** [comment]
These errors go away by simply changing these lines in `driver.py` and `monitor.py`
```
(driver.py)
from cocotb.drivers import BusDriver
(monitor.py)
from cocotb.monitors import BusMonitor
```
to
```
(driver.py)
from cocotb_bus.drivers import BusDriver
(monitor.py)
from cocotb_bus.monitors import BusMonitor
```

I did this in my Wishbone-based project using cocotb 1.6.0, and everything seemed to work fine.

**Comment by Martoni** [comment]
Hi @thejpster & @Roenski.
@akukulanski PR is finally merged.
Sorry for the delay
